version: '3.2'

services:
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    volumes:
      - ./docker/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./docker/grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./docker/grafana/dashboards/create_session.json:/etc/grafana/provisioning/dashboards/create_session.json

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'