version: '3.2'

services:
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    volumes:
      - ./docker/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./docker/grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./docker/grafana/dashboards/create_session.json:/etc/grafana/provisioning/dashboards/create_session.json

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  hazelcast-mgmt:
    image: hazelcast/management-center:3.12.8
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Dhazelcast.mc.healthCheck.enable=true --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
      - MC_INIT_CMD=/opt/hazelcast/mancenter/mc-conf.sh create-user -H=/data -n=amplifix -p=ampx2020 -r=admin -v

  load-balancer:
    image: nginx
    ports:
      - "5000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf